num = input("Enter your phone number: ")
print("You entered: " + num)
print("Number of Digits: " + str(len(num)))
print("First Digit: " + num[0])
print("Last Digit: " + num[-1])
print("Middle Digits: " + num[1:-1])
print("Reversed Number: " + num[::-1])
print("Number in Uppercase: " + num.upper())
print("Number in Lowercase: " + num.lower())
print("Is Numeric: " + str(num.isnumeric()))
print("Is Alphabetic: " + str(num.isalpha()))